# Generated by Django 2.2.28 on 2026-02-13 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ('title',)},
        ),
    ]
